# Generated by Django 5.1.1 on 2024-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulbState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
