# Generated by Django 5.1.1 on 2024-09-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_bulbstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TURN_ON', 'Turn On'), ('TURN_OFF', 'Turn Off')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
